version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ridesharing-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    container_name: ridesharing-redis
    ports:
      - "6380:6379"

volumes:
  postgres-data:
